// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UcakRezervasyon.Data;

#nullable disable

namespace UcakRezervasyon.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231227103142_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Uçakrezervasyon.Models.guzergah", b =>
                {
                    b.Property<int>("guzergahId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("guzergahId"));

                    b.HasKey("guzergahId");

                    b.ToTable("guzergah");
                });

            modelBuilder.Entity("Uçakrezervasyon.Models.ucak", b =>
                {
                    b.Property<int>("ucakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ucakId"));

                    b.Property<int>("koltukSayisi")
                        .HasColumnType("int");

                    b.Property<string>("ucakName")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("ucakId");

                    b.ToTable("ucak");
                });

            modelBuilder.Entity("Uçakrezervasyon.Models.ucakdetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("ucakdetay");
                });

            modelBuilder.Entity("Uçakrezervasyon.Models.ucus", b =>
                {
                    b.Property<int>("ucusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ucusId"));

                    b.Property<int>("guzergahId")
                        .HasColumnType("int");

                    b.Property<int>("koltukNo")
                        .HasColumnType("int");

                    b.Property<int>("ucakId")
                        .HasColumnType("int");

                    b.HasKey("ucusId");

                    b.ToTable("ucus");
                });
#pragma warning restore 612, 618
        }
    }
}
