// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UcakRezervasyon.Data;

#nullable disable

namespace UcakRezervasyon.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231227194927_AddNewPropertyToGuzergah")]
    partial class AddNewPropertyToGuzergah
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UcakRezervasyon.Models.guzergah", b =>
                {
                    b.Property<int>("guzergahId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("guzergahId"), 1L, 1);

                    b.Property<string>("guzergahName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("guzergahId");

                    b.ToTable("guzergah");
                });

            modelBuilder.Entity("UcakRezervasyon.Models.ucak", b =>
                {
                    b.Property<int>("ucakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ucakId"), 1L, 1);

                    b.Property<int>("koltukSayisi")
                        .HasColumnType("int");

                    b.Property<string>("ucakName")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("ucakId");

                    b.ToTable("ucak");
                });

            modelBuilder.Entity("UcakRezervasyon.Models.ucakdetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("ucakdetay");
                });

            modelBuilder.Entity("UcakRezervasyon.Models.ucus", b =>
                {
                    b.Property<int>("ucusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ucusId"), 1L, 1);

                    b.Property<int>("guzergahId")
                        .HasColumnType("int");

                    b.Property<int>("koltukNo")
                        .HasColumnType("int");

                    b.Property<int>("ucakId")
                        .HasColumnType("int");

                    b.HasKey("ucusId");

                    b.ToTable("ucus");
                });
#pragma warning restore 612, 618
        }
    }
}
